# This compose file is for testing and development.
# The configuration used for the database is not intended for production
# /opt/filerouter is where the application is stored and run out of per the Dockerfile
---
version: '2'
services:
  redis:
    image: redis:latest

  postgres:
    image: postgresql:11-alpine
    volumes: [ './db/pg_data:/var/lib/postgresql/data' ]
    environment:
      - POSTGRES_PASSWORD=password

  sidekiq:
    build: .
    volumes: .:/opt/filerouter
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=development
    links:
      - postgres
      - redis

  filerouter:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
    volumes: .:/opt/filerouter
    links:
      - postgres
      - redis
