# FileRouter base configuration
providers:
  remote:
    - FileRouter::Remote::SFTP
    - FileRouter::Remote::SFTPWithPGP
    - FileRouter::Remote::FTP
    - FileRouter::Remote::FTPWithPGP
    - FileRouter::Remote::HTTPPost
  repository:
    - FileRouter::Repository::Local

